project_name: flowerss-bot

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download

builds:
  - id: darwin
    ldflags: -s -w -X github.com/indes/flowerss-bot/config.version={{.Version}} -X github.com/indes/flowerss-bot/config.date={{.Date}} -X github.com/indes/flowerss-bot/config.commit={{ .ShortCommit }}
    goos:
      - darwin
    goarch:
      - amd64

  - id: linux
    ldflags: -s -w -X github.com/indes/flowerss-bot/config.version={{.Version}} -X github.com/indes/flowerss-bot/config.date={{.Date}} -X github.com/indes/flowerss-bot/config.commit={{ .ShortCommit }}
    goos:
      - linux
    goarch:
      - amd64

  - id: windows
    ldflags: -s -w -X github.com/indes/flowerss-bot/config.version={{.Version}} -X github.com/indes/flowerss-bot/config.date={{.Date}} -X github.com/indes/flowerss-bot/config.commit={{ .ShortCommit }}
    goos:
      - windows
    goarch:
      - amd64


archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
      dragonfly: DragonFlyBSD
    files:
      - README.md
      - config.yml.sample
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^dev:'
      - 'README'
      - Merge pull request
      - Merge branch